### ISSUE TITLE
No Enchanted Gravitite in Aether Redux

### ISSUE THREAD

**Issue by Daaf-it** [Syrikal/Aetheric-Tetranomicon#2]
Aether Redux changes the Enchanted Gravitite recipe, it will now produce Gravitite Ingot which does not work in the Tetra Workbench.
This makes it imposible to put Gravitite on tools since the block that the Tetra Workbench is looking for is not obtainable.

**Comment by Syrikal** [comment]
Fixed in 1.1.2.
