### ISSUE TITLE
loading failed in 1.19.2

### ISSUE THREAD

**Issue by hyygybs** [Syrikal/Aetheric-Tetranomicon#3]
the crashed report is wrong.

**Comment by Syrikal** [comment]
This looks like a crash involving Every Compat and Quark. Confirm that the crash happens with nothing but Tetra, the Aether, and Aetheric Tetranomicon, OR - if removing Aetheric Tetranomicon fixes it - exactly which mods must be present for Aetheric Tetranomicon to cause a crash. If I don't have that, I can't do anything.

**Comment by hyygybs** [comment]
it crashed with only mutils, Tetra, the Aether, and Aetheric Tetranomicon.
[latest.log](https://github.com/Syrikal/Aetheric-Tetranomicon/files/14831043/latest.log)

**Comment by Syrikal** [comment]
Oh that _does_ look like my fault. I'll get right on it.

**Comment by Syrikal** [comment]
The fix is being difficult, but for now the workaround is to use Forge 43.2.0. I can confirm it works fine there but breaks in Forge 43.3.0.

**Comment by Syrikal** [comment]
OK, a fix is proving difficult at the moment, but the issue is Forge 43.3.0. Aetheric Tetranomicon works fine in 43.2.0, if you want to use that while you wait for a fix.

**Comment by Syrikal** [comment]
Try using the latest alpha version (1.1.2) and see if that fixes it.

**Comment by hyygybs** [comment]
ok, i try it and it is fixed.
