### ISSUE TITLE
+1 Loading Crash: Exit Code 1 in 1.19.2

### ISSUE THREAD

**Issue by AmazeingGames** [Syrikal/Aetheric-Tetranomicon#4]
Game Version: 1.19.2
Forge Version: 43.3.0
[Crash Report](https://pastebin.com/LkQYPKsX)

Mod List:
[tetra-1.19.2-5.6.0](https://www.curseforge.com/minecraft/mc-mods/tetra/files/4941337)
[mutil-1.19.2-5.2.0](https://www.curseforge.com/minecraft/mc-mods/mutil/files/4941248)
[aetheric_tetranomicon-1.1.1-1.19.2](https://www.curseforge.com/minecraft/mc-mods/aetheric-tetranomicon/files/5221733)
[aether-1.19.2-1.3.1-forge](https://www.curseforge.com/minecraft/mc-mods/aetheric-tetranomicon/files/5221733)

No other mods were in the folder at the time of the crash.

**Comment by Syrikal** [comment]
Duplicate of #3

**Comment by Syrikal** [comment]
Use 1.1.2 (alpha, uploaded to CurseForge) and let me know if that fixes it.

**Comment by AmazeingGames** [comment]
> Use 1.1.2 (alpha, uploaded to CurseForge) and let me know if that fixes it.

Appreciate it! I don't see a download on the page quite yet; may I have the link?

**Comment by AmazeingGames** [comment]
Apologies, I tested the latest and it runs and works in my mod list
